### PR TITLE
add support for smart text

### PR DESCRIPTION
**Pull request by maletor**

### CODE REVIEW

**Comment by hd-deman** [comment]
@lloeki don't forget to update notable changes in releases when you publish something new release and update release draft if you merge PRs. https://github.com/AtomLinter/linter-slim/releases

**Comment by lloeki** [comment]
@hd-deman Got it, although honestly I built this package out of pure frustration. With free time becoming increasingly scarce for me, if anyone is stepping up I'd gladly pass maintainership on.

**Comment by maletor** [comment]
I have some time to handle it if you want. We use hundreds of Slim templates at my place of work.

**Comment by lloeki** [comment]
Let's do this. @maletor, you are now bestowed maintainer of this project.

**Pull request merged**
